#!/bin/bash

ModulesDir=/usr/share/tomcat7/.OpenMRS/modules
#OmodTmpDir=/tmp/openmrs-omods
#
#mkdir -p ${BundledModulesDir}
#cp ${OmodTmpDir}/** ${BundledModulesDir}
chown -R tomcat7:tomcat7 ${ModulesDir}
##restart tomcat
/etc/init.d/tomcat7 restart