import { type StockItemDTO } from '../../core/api/types/stockItem/StockItem';

export const initialValues: StockItemDTO = {
  uuid: undefined,
  isDrug: undefined,
  drugUuid: undefined,
  drugName: undefined,
  conceptUuid: undefined,
  commonName: undefined,
  acronym: undefined,
  conceptName: undefined,
  hasExpiration: undefined,
  preferredVendorUuid: undefined,
  preferredVendorName: undefined,
  purchasePrice: undefined,
  purchasePriceUoMUuid: undefined,
  purchasePriceUoMName: undefined,
  dispensingUnitName: undefined,
  dispensingUnitUuid: undefined,
  dispensingUnitPackagingUoMUuid: undefined,
  dispensingUnitPackagingUoMName: undefined,
  defaultStockOperationsUoMUuid: undefined,
  defaultStockOperationsUoMName: undefined,
  reorderLevel: undefined,
  reorderLevelUoMUuid: undefined,
  reorderLevelUoMName: undefined,
  dateCreated: undefined,
  creatorGivenName: undefined,
  creatorFamilyName: undefined,
  voided: undefined,
  packagingUnits: undefined,
  permission: undefined,
  categoryUuid: undefined,
  categoryName: undefined,
  expiryNotice: undefined,
};
