global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox-http-prod'
    metrics_path: /probe
    params:
      module: [ http_2xx_ignore_ssl ]
    static_configs:
      - targets:
          - "http://gateway:80/"
          - "http://gateway:80/openmrs"
          - "http://gateway:80/openmrs/ws/rest/v1/session"
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115