FROM httpd:2.4

COPY ./proxy/httpd.conf /usr/local/apache2/conf/httpd.conf

# Remove ununsed configs
RUN rm -rf /usr/local/apache2/conf/extra/*

# Add our proxy Vhost
COPY ./proxy/proxy.conf /usr/local/apache2/conf/extra/proxy.conf
