<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.openmrs.module</groupId>
		<artifactId>labtestreport</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>labtestreport-api</artifactId>
	<packaging>jar</packaging>
	<name>Lab Test Report Module API</name>
	<description>API project for the Lab Test Summary Report module</description>

	<dependencies>
		<dependency>
			<groupId>org.openmrs.api</groupId>
			<artifactId>openmrs-api</artifactId>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.openmrs.web</groupId>
			<artifactId>openmrs-web</artifactId>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.openmrs.module</groupId>
			<artifactId>reporting-api</artifactId>
		</dependency>
	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
	</build>

	<properties>
		<MODULE_ID>${project.parent.artifactId}</MODULE_ID>
		<MODULE_NAME>${project.parent.name}</MODULE_NAME>
		<MODULE_VERSION>${project.parent.version}</MODULE_VERSION>
		<MODULE_PACKAGE>${project.parent.groupId}.${project.parent.artifactId}</MODULE_PACKAGE>
	</properties>

</project>
