FROM nginx:1.21-alpine

RUN apk update && \
    apk upgrade && \
    # add more utils for sponge to support our startup script
    apk add --no-cache moreutils

# clear any default files installed by nginx
RUN rm -rf /usr/share/nginx/html/*

COPY ./ui/startup.sh /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/startup.sh

COPY ./ui/nginx.conf /etc/nginx/nginx.conf

# actually load the distribution into the image
ADD ./distro/spa /usr/share/nginx/html/

CMD ["/usr/local/bin/startup.sh"]
