CHANGE MASTER TO 
  MASTER_HOST='db',
  MASTER_USER='${OMRS_DB_REPL_USER:-openmrs_repl}',
  MASTER_PASSWORD='${OMRS_DB_REPL_PASSWORD:-openmrs_repl}',
  MASTER_PORT=3306;  
FLUSH PRIVILEGES;
START SLAVE;
SHOW SLAVE STATUS;
