name=Ref 3.x distro
version=${project.version}
war.openmrs=${openmrs.version}
omod.spa=${spa.version}
omod.initializer=${initializer.version}
omod.fhir2=${fhir2.version}
omod.webservices.rest=${webservices.rest.version}
omod.idgen=${idgen.version}
omod.legacyui=${legacyui.version}
omod.addresshierarchy=${addresshierarchy.version}
omod.patientdocuments=${patientdocuments.version}
omod.metadatamapping=${metadatamapping.version}
omod.openconceptlab=${openconceptlab.version}
omod.attachments=${attachments.version}
omod.queue=${queue.version}
omod.appointments=${appointments.version}
omod.appointments.groupId=org.bahmni.module
omod.teleconsultation=${teleconsultation.version}
omod.teleconsultation.groupId=org.bahmni.module
omod.cohort=${cohort.version}
omod.reporting=${reporting.version}
omod.reportingrest=${reportingrest.version}
omod.calculation=${calculation.version}
omod.htmlwidgets=${htmlwidgets.version}
omod.serialization.xstream=${serialization-xstream.version}
omod.serialization.xstream.type=omod
omod.ordertemplates=${ordertemplates.version}
omod.patientflags=${patientflags.version}
omod.o3forms=${o3forms.version}
omod.authentication=${authentication.version}
omod.emrapi=${emrapi.version}
omod.event.groupId=org.openmrs
omod.event=${event.version}
omod.bedmanagement=${bedmanagement.version}
omod.stockmanagement=${stockmanagement.version}
omod.billing=${billing.version}
omod.tasks=${tasks.version}
content.referenceapplication=${reference-content.version}
spa.core=next
spa.frontendModules.@openmrs/esm-active-visits-app=next
spa.frontendModules.@openmrs/esm-appointments-app=next
spa.frontendModules.@openmrs/esm-bed-management-app=next
spa.frontendModules.@openmrs/esm-billing-app=next
spa.frontendModules.@openmrs/esm-cohort-builder-app=next
spa.frontendModules.@openmrs/esm-devtools-app=next
spa.frontendModules.@openmrs/esm-dispensing-app=next
spa.frontendModules.@openmrs/esm-fast-data-entry-app=next
spa.frontendModules.@openmrs/esm-form-builder-app=next
spa.frontendModules.@openmrs/esm-form-engine-app=next
spa.frontendModules.@openmrs/esm-generic-patient-widgets-app=next
spa.frontendModules.@openmrs/esm-help-menu-app=next
spa.frontendModules.@openmrs/esm-home-app=next
spa.frontendModules.@openmrs/esm-implementer-tools-app=next
spa.frontendModules.@openmrs/esm-laboratory-app=next
spa.frontendModules.@openmrs/esm-login-app=next
spa.frontendModules.@openmrs/esm-openconceptlab-app=next
spa.frontendModules.@openmrs/esm-patient-allergies-app=next
spa.frontendModules.@openmrs/esm-patient-attachments-app=next
spa.frontendModules.@openmrs/esm-patient-banner-app=next
spa.frontendModules.@openmrs/esm-patient-chart-app=next
spa.frontendModules.@openmrs/esm-patient-conditions-app=next
spa.frontendModules.@openmrs/esm-patient-flags-app=next
spa.frontendModules.@openmrs/esm-patient-forms-app=next
spa.frontendModules.@openmrs/esm-patient-immunizations-app=next
spa.frontendModules.@openmrs/esm-patient-label-printing-app=next
spa.frontendModules.@openmrs/esm-patient-list-management-app=next
spa.frontendModules.@openmrs/esm-patient-lists-app=next
spa.frontendModules.@openmrs/esm-patient-medications-app=next
spa.frontendModules.@openmrs/esm-patient-notes-app=next
spa.frontendModules.@openmrs/esm-patient-orders-app=next
spa.frontendModules.@openmrs/esm-patient-programs-app=next
spa.frontendModules.@openmrs/esm-patient-registration-app=next
spa.frontendModules.@openmrs/esm-patient-search-app=next
spa.frontendModules.@openmrs/esm-patient-tests-app=next
spa.frontendModules.@openmrs/esm-patient-vitals-app=next
spa.frontendModules.@openmrs/esm-primary-navigation-app=next
spa.frontendModules.@openmrs/esm-reports-app=next
spa.frontendModules.@openmrs/esm-service-queues-app=next
spa.frontendModules.@openmrs/esm-stock-management-app=next
spa.frontendModules.@openmrs/esm-system-admin-app=next
spa.frontendModules.@openmrs/esm-task-list-app=next
spa.frontendModules.@openmrs/esm-user-onboarding-app=next
spa.frontendModules.@openmrs/esm-ward-app=next
